### PR TITLE
3 Examples with Metadata: Semantic Text Search, Jeopardy Board Creation, and Image Search 

### PR DESCRIPTION
**Pull request by startakovsky**
@gkogan This PR is ready for merging to your master repository. The notebooks are readied for the master branch (i.e. pointing to the correct location of _helper.py_).

Here are the components, all in one pull request that has been reviewed by @jamescalam and polished off by me:

These examples have all been (re)created, featuring metadata usage using canonical, easy-to-download models and datasets:
  1) _semantic_text_search_
  2) _jeopardy_
  3) _image search_
  4) convenience technical component: Colab Badge GitHub Action (will automatically generate a colab link when writing `{{ badge }}` in a markdown cell. Can also be used to refer to other notebooks, makes life easier Read more [here](https://github.com/trsvchn/colab-badge-action). 
   ** @gkogan You may need to scroll down [here](https://github.com/pinecone-io/examples/settings/actions) to change permissions. You will want to enable read/write access to the Colab Badge action.

### CODE REVIEW

**Comment by jamescalam** [comment]
@gkogan okay to merge for me

**Comment by startakovsky** [comment]
@gkogan @jamescalam I have merged image search into this pull request, and updated its title and body accordingly. Let me know any final feedback or iterations, I'm looking forward to wrapping this up!

**Comment by jamescalam** [comment]
Looks great thanks @startakovsky! I'm merging

**Comment by startakovsky** [comment]
Thanks @jamescalam! Awesome.

**Pull request merged**
