### PR TITLE
Add code for querying existing index w/Llama

### PR DESCRIPTION
**Pull request by aulorbe**
## Problem

Users often don't know the best way to query an existing Pinecone index via LlamaIndex. This code snippet does that + shows how to do it with a Pinecone index that contains namespaces.

## Solution

Describe the approach you took. Link to any relevant bugs, issues, docs, or other resources.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

Will run by LlamaIndex devs in our shared channel to confirm its validity :)

### CODE REVIEW

**Comment by jamescalam** [comment]
* naming conventions for repo are to use all lowercase and "-" rather than "_" — former is so we don't need to think about title case or anything other standard (other than all lower), latter is a [Google recommended thing for URLs](https://developers.google.com/search/docs/crawling-indexing/url-structure#:~:text=We%20recommend%20that%20you%20use,(%20_%20)%20in%20your%20URLs.)
* your file is weird:
image

**Comment by jamescalam** [comment]
@aulorbe you have merge changes in the file, causing the error
image

**Comment by aulorbe** [comment]
Sry about that @jamescalam all fixed now :)

**Comment by aulorbe** [comment]
Oof, rebased & now have your commits @jamescalam don't think it's make or break, but sry about the complicated commit history

**Comment by jamescalam** [comment]
@aulorbe you did make this complicated 😅 — all looks good to me!

**Pull request merged**
