### PR TITLE
Simplified code for deduplication example

### PR DESCRIPTION
**Pull request by ashraq1455**

### CODE REVIEW

**Review by jamescalam — APPROVED** [review]
Looks good to me, I also got permission from CORE to add their deduplication dataset to HuggingFace, will that simplify the notebook? One thing is I don't think people running on windows have the `!wget` comment (I could be wrong)

**Comment by ashraq1455** [comment]
> Looks good to me, I also got permission from CORE to add their deduplication dataset to HuggingFace, will that simplify the notebook? One thing is I don't think people running on windows have the `!wget` comment (I could be wrong)

Just checked. It seems wget is not natively supported in windows. But curl and tar seems to be preinstalled in windows 10. Shall i test it and change?

For this project i don't think uploading dataset to HF will simplify anymore (i could be wrong). I have already simplified it to use one liner to load into pandas df.

I think we could simplify further if we use pinecone metadata storage. But some texts in the dataset exceeds max metadata size. So couldn’t do that.

**Comment by jamescalam** [comment]
@ashraq1455 given that wget isn't natively supported, I've ported the dataset over to Hugging Face and added the necessary download script in the notebook. I have also modified the script to add metadata to Pinecone, this needed two changes:

* Use selective metadata, meaning we can store metadata that *is not* indexed, non-indexed metadata has a memory limit of 10KB per vector
* 10KB is more than enough for *most* items with the exception of at least one record that reached 12KB for some reason, so I added truncation to the processed_abstract feature to limit it to 8000 characters

I haven't had time to confirm that the metadata is correctly working nor update the remaining 'testing' of the notebook to use this new source of metadata (rather than local), @ashraq1455 are you able to do that?

**Comment by ashraq1455** [comment]
> @ashraq1455 given that wget isn't natively supported, I've ported the dataset over to Hugging Face and added the necessary download script in the notebook. I have also modified the script to add metadata to Pinecone, this needed two changes:
> 
> * Use selective metadata, meaning we can store metadata that _is not_ indexed, non-indexed metadata has a memory limit of 10KB per vector
> * 10KB is more than enough for _most_ items with the exception of at least one record that reached 12KB for some reason, so I added truncation to the processed_abstract feature to limit it to 8000 characters
> 
> I haven't had time to confirm that the metadata is correctly working nor update the remaining 'testing' of the notebook to use this new source of metadata (rather than local), @ashraq1455 are you able to do that?
> 
> Let me know if there are any issues!

Thanks. I will test it and change the code to use selective metadata.

**Comment by ashraq1455** [comment]
@jamescalam I could not find anywhere we can use metadata filtering in this example. But storing "processed_abstract" in Pinecone index greatly speeded up things as previously we had to search through the pandas df (which was slow) to find "processed_abstract" for relevant "id" when printing the results. Let me know if you have any idea where we can use metadata filtering.

The notebook is fully tested and runs the same as before.

**Review by jamescalam — APPROVED** [review]
@ashraq1455 great work, I'll merge it - thanks!

**Pull request merged**
