### PR TITLE
Added notebook usability updates for Tatoeba example

### PR DESCRIPTION
**Pull request by arjunpatel7**
## Problem

Notebook was hard to use prior, probably impacted ease of use. 
## Solution

Added Pinecone Connect, open in colab button, and
pip install pinecone for better useability
## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

Run the notebook from top to bottom, works.

### CODE REVIEW

**Comment by jseldess** [comment]
Unrelated to the changes in this PR, but can you change `if index_name not in pc.list_indexes().names():` to the new syntax: `if not pc.has_index(index_name):`?

**Review by jseldess — APPROVED** [review]
LGTM!

But there are a few empty code blocks that say "Start coding or generate with AI" that you might want to remove.

**Comment by arjunpatel7** [comment]
Hi @jseldess , just added that!

**Comment by arjunpatel7** [comment]
and empty blocks are now gone!

**Pull request merged**
