### PR TITLE
Add Canopy x AzureOpenAI Studio demo notebook

### PR DESCRIPTION
**Pull request by aulorbe**
## Problem

This notebook accompanies the Canopy x Azure OpenAI blog post ([forthcoming](https://docs.google.com/document/d/1HC2zVk4QkG0rWWQD0ZL3ann_DjGykEM0JLHFL4QszA8/edit)). 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

@rschwabco has already run nb e2e. Will ask that formal reviewer here also runs nb e2e to ensure it works.

### CODE REVIEW

**Comment by aulorbe** [comment]
> #### ⚠️ GitGuardian has uncovered 2 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 
> GitGuardian id	GitGuardian status	Secret	Commit	Filename	
> [9557865](https://dashboard.gitguardian.com/incidents/9557865?occurrence=124761751)	Triggered	Pinecone API Key	[9ecdb92](https://github.com/pinecone-io/examples/commit/9ecdb92bbc9f83755ae234b6326dd3af38d47cc3)	learn/generation/canopy/canopy-azure-openai-studio/canopy-azure-openai.ipynb	[View secret](https://github.com/pinecone-io/examples/commit/9ecdb92bbc9f83755ae234b6326dd3af38d47cc3#diff-86ca2a1b7fc0d6fd00e628dabcdee9bf19b38c0a81c1fd26aa04ad8eedc00090R155)
> [9557866](https://dashboard.gitguardian.com/incidents/9557866?occurrence=124761750)	Triggered	Generic High Entropy Secret	[9ecdb92](https://github.com/pinecone-io/examples/commit/9ecdb92bbc9f83755ae234b6326dd3af38d47cc3)	learn/generation/canopy/canopy-azure-openai-studio/canopy-azure-openai.ipynb	[View secret](https://github.com/pinecone-io/examples/commit/9ecdb92bbc9f83755ae234b6326dd3af38d47cc3#diff-86ca2a1b7fc0d6fd00e628dabcdee9bf19b38c0a81c1fd26aa04ad8eedc00090R156)
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

Ugh shoot. Will rotate keys. Have now removed from notebook.

**Comment by aulorbe** [comment]
@igiloh-pinecone for visibility :)

**Comment by jamescalam** [comment]
@aulorbe seeing this issue:
image

**Comment by aulorbe** [comment]
> @aulorbe seeing this issue: image

As yes, that's b/c if you run the notebook e2e, you've already initialized the tokenizer. I'll make it a try stmt!

**Review by jamescalam — APPROVED** [review]

**Pull request merged**
